package com.tcs.ilp.servease.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.tcs.ilp.servease.entity.BillUser;

@Repository
public interface BillUserRepository extends JpaRepository<BillUser, String> {

    // ✅ Custom method (auto-generated by Spring)
    BillUser findByAssignmentId(String assignmentId);
}